server:
  port: 8001
  instance:
    instance-id: user-provider-8001 # 自定义服务名称信息

mybatis:
  # mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 驼峰自动映射
    map-underscore-to-camel-case: true


spring:
  application:
    name: user-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://localhost:3306/test        # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5               # 数据库连接池的最小维持连接数
      initial-size: 5           # 初始化连接数
      max-total: 5              # 最大连接数
      max-wait-millis: 200      # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true