server:
  port: 8001
  instance:
    instance-id: user-provider-8001 # 自定义服务名称信息

mybatis:
  # mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 驼峰自动映射
    map-underscore-to-camel-case: true


spring:
  application:
    name: user-provider
  profiles:
    active: prd

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true